### ISSUE TITLE
Can we have the page scroll to the top of the active panel when you click to open it?

### ISSUE THREAD

**Issue by dkmartin** [michu2k/HUE#5]
When you click to open a panel, can we have the page scroll to the top of the active panel, so you don't have to manually scroll up when the content of the previous panel is really long?

**Comment by michu2k** [comment]
Hi
Thank you for your post. I'll think about this idea.

**Comment by dkmartin** [comment]
In the meantime, if anyone is interested in this:

`$('.accordion-container .ac-q').bind('click',function(){
            var self = this;
            var headerHeight = $('#header-control-panel').height();
            setTimeout(function() {
                theOffset = $(self).offset();
                $('body,html').animate({ scrollTop: theOffset.top - headerHeight - 100 });
            }, 510); // ensure the collapse animation is done
        });`

Slightly modified from https://www.sitepoint.com/community/t/fiddle-me-this-jquery-accordion-scroll-beginning-of-clicked-tab-to-the-top/36132

**Comment by michu2k** [comment]
Hey
I decided not to implement your idea, but i really appreciate your post. Tomorrow will be version 2.5 with code fixes and some ARIA support :).
