### ISSUE TITLE
Accordions break unless all defined containers appear on page

### ISSUE THREAD

**Issue by andrewlobo** [michu2k/HUE#83]
I have multiple accordions that appear on different pages. I would like to define all of the containers that appear everywhere on the website, but this breaks unless all of the accordion containers appear on a page.

Suppose I have defined these three accordions for the whole website:

```
new Accordion(['.container1', '.container2', '.container3'], {
  duration: 400
});
```

And on page 1, I have container markup for `.container1` and `.container2`, this will work.

But if I have container markup on page 1 for `.container2` and `.container3`, they will break because the first container (i.e. `.container1`) does not appear.

Likewise, if I have container markup for `.container1` and `.container3`, then `.container1` will work, but `.container3` will break because `.container2` does not appear on the page.

Even if I have a totally empty `div` with a class of `.container2`, this is enough to make `.container3` work.

Hope I explained it all right. By the way, this is a great module. So helpful.

**Comment by michu2k** [comment]
Hi @andrewlobo
You can pass an array of nodes, so only found elements will be passed to the Accordion().

```js
  const accordions = [...document.querySelectorAll('.container')];
  new Accordion(accordions);
```

**Comment by andrewlobo** [comment]
That works. I couldn’t tell what that array in the docs was for. Thanks very much.
